### ISSUE TITLE
Proposal: Allow senior staff and managers to edit Bugzilla components

### ISSUE THREAD

**Issue by emceeaich** [mozilla-conduit/developer-productivity-rfcs#6]

**Comment by mitchhentges** [comment]
Hey, thanks for creating an RFC! :tada:
My interpretation of the [mechanics](https://github.com/mozilla-conduit/developer-productivity-rfcs/blob/master/mechanics.md) are that creating a Github issue is good if you need to gather more data and discussion to create a proposal. It looks like in this case a proposal is already available [here](https://github.com/mozilla-conduit/developer-productivity-rfcs/pull/7), so I don't believe that this issue is needed :smile:

Discussion on the proposal can all happen on the PR at this point, IMHO

**Comment by emceeaich** [comment]
Thanks for clarifying that. Should I close this issue with a note directing to the PR?

**Comment by mitchhentges** [comment]
That would be great!

**Comment by emceeaich** [comment]
Moved to #7
